# Generated by Django 2.2.5 on 2019-09-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banlist',
            name='ip',
            field=models.ManyToManyField(blank=True, to='user.IPlist'),
        ),
        migrations.AlterField(
            model_name='banlist',
            name='user',
            field=models.ManyToManyField(blank=True, to='user.Profile'),
        ),
    ]
